name: Backwards Compatibility Tests NeuralSearch
on:
  push:
    branches:
      - "*"
      - "feature/**"
  pull_request:
    branches:
      - "*"
      - "feature/**"

jobs:
  Restart-Upgrade-BWCTests-NeuralSearch:
    strategy:
      matrix:
        # Restricting java 21 to 21.0.1 due to ongoing bug in JDK 21.0.2 https://bugs.openjdk.org/browse/JDK-8323659. Once the fix https://github.com/opensearch-project/OpenSearch/pull/11968 get merged this change will be reverted.
        java: [ 11, 17, 21.0.1 ]
        os: [ubuntu-latest,windows-latest]
        bwc_version : ["2.9.0","2.10.0","2.11.0","2.12.0-SNAPSHOT"]
        opensearch_version : [ "3.0.0-SNAPSHOT" ]

    name: NeuralSearch Restart-Upgrade BWC Tests
    runs-on: ${{ matrix.os }}
    env:
      BWC_VERSION_RESTART_UPGRADE: ${{ matrix.bwc_version }}

    steps:
      - name: Checkout neural-search
        uses: actions/checkout@v1

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Run NeuralSearch Restart-Upgrade BWC Tests from BWCVersion-${{ matrix.bwc_version }} to OpenSearch Version-${{ matrix.opensearch_version }} on ${{matrix.os}}
        run: |
          echo "Running restart-upgrade backwards compatibility tests ..."
#          Disabling BWC tests due to ongoing build failure. https://github.com/opensearch-project/neural-search/issues/536
#          ./gradlew :qa:restart-upgrade:testAgainstNewCluster -D'tests.bwc.version=${{ matrix.bwc_version }}'

  Rolling-Upgrade-BWCTests-NeuralSearch:
    strategy:
      matrix:
        java: [ 11, 17, 21 ]
        os: [ubuntu-latest,windows-latest]
        bwc_version: [ "2.12.0-SNAPSHOT" ]
        opensearch_version: [ "3.0.0-SNAPSHOT" ]

    name: NeuralSearch Rolling-Upgrade BWC Tests
    runs-on: ${{ matrix.os }}
    env:
      BWC_VERSION_ROLLING_UPGRADE: ${{ matrix.bwc_version }}

    steps:
      - name: Checkout neural-search
        uses: actions/checkout@v1

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Run NeuralSearch Rolling-Upgrade BWC Tests from BWCVersion-${{ matrix.bwc_version }} to OpenSearch Version-${{ matrix.opensearch_version }} on ${{matrix.os}}
        run: |
          echo "Running rolling-upgrade backwards compatibility tests ..."
#          Disabling BWC tests due to ongoing build failure. https://github.com/opensearch-project/neural-search/issues/536
#         ./gradlew :qa:rolling-upgrade:testRollingUpgrade -D'tests.bwc.version=${{ matrix.bwc_version }}'
