name: Build and Test Neural Search
on:
  schedule:
    - cron: '0 0 * * *'  # every night
  push:
    branches:
      - "*"
      - "feature/**"
  pull_request:
    branches:
      - "*"
      - "feature/**"

jobs:
  Check-neural-search:
    strategy:
      matrix:
        java: [11, 17]
        os: [ubuntu-latest, windows-latest]

    name: Run Gradle Check on neural-search Plugin
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout neural-search
        uses: actions/checkout@v1

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Run build
        run: |
          ./gradlew check

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  Precommit-neural-search:
    strategy:
      matrix:
        java: [11, 17]
        os: [ubuntu-latest, windows-latest]

    name: Pre-commit neural-search Plugin
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout neural-search
        uses: actions/checkout@v1

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Run build
        run: |
          ./gradlew precommit --parallel

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
